### ISSUE TITLE
Jornada do usuário

### ISSUE THREAD

**Issue by Murilo-ZC** [2023M8T2-Inteli/andevs#1]
Pessoal eu acho que um ponto pode ser alterado na jornada. O Mauro, persona de vocês, precisaria ter acesso a relatórios que pudessem demonstrar esses avanços e evoluções. Acredito que ele fica melhor na persona de Eng. de Manutenção. Acredito que o técnico de manutenção deveria ter um ganho mais direto no seu dia a dia durante a realização das manutenções.

**Comment by joaocarazzato** [comment]
@riqueschilder
