### ISSUE TITLE
Descrição mais incrementada de negócios

### ISSUE THREAD

**Issue by taiinteli** [2023M8T2-Inteli/andevs#4]

**Comment by joaocarazzato** [comment]
Matriz de riscos: Feita ✔️
Matriz Oceano Azul(Kil): Fazendo ➖
Canvas Proposta de Valor(Kil): Fazendo ➖

**Comment by joaocarazzato** [comment]
https://github.com/2023M8T2-Inteli/andevs/commit/1bb95c70d7870f20d4d9886ca2520c57fed71fe6
https://github.com/2023M8T2-Inteli/andevs/commit/8f672382140f43ff6ffc1807b538efcf97c55363
